cd lib

BuildAudioArchive.bat

BuildDSSpriteArchive.bat
BuildGBASpriteArchive.bat

BuildTilesArchive.bat

BuildBattleScriptArchive.bat
BuildBattleAnimationScriptArchive.bat
BuildOverworldScriptArchive.bat